
[hasura]
version = 'v2.44.0-ce'
adminSecret = '{{ secrets.HASURA_GRAPHQL_ADMIN_SECRET }}'
webhookSecret = '{{ secrets.NHOST_WEBHOOK_SECRET }}'

[[hasura.jwtSecrets]]
type = "HS256"
key = "8f9a2b3c4d5e6f7a8b9c0d1e2f3a4b5c6d7e8f9a"


[hasura.settings]
corsDomain = ['*']
devMode = true
enableAllowList = false
enableConsole = true
enableRemoteSchemaPermissions = false
enabledAPIs = ['metadata', 'graphql', 'pgdump', 'config']

[functions]
[functions.node]
version = 20

[auth]
[auth.method]
[auth.method.emailPassword]
emailVerificationRequired = false
hibpEnabled = false

[auth.method.anonymous]
enabled = true

[auth.redirections]
clientUrl = 'http://localhost:3000'

[postgres]
version = '14.11-20240515-1'

[storage]
version = '0.6.1'

[[global.environment]]
name = 'GROQ_API_KEY'
value = '{{ secrets.GROQ_API_KEY }}'

[[global.environment]]
name = 'OPENROUTER_API_KEY'
value = '{{ secrets.OPENROUTER_API_KEY }}'
